server:
  port: 8085

spring:
  profiles:
    active: development

---
spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            authorizationGrantType: authorization_code
            clientId: e0e8f2ba6891421fbf9369672b356372
            clientSecret: a8c864b33a7e422f94c7e04a121230a3
            redirect-uri: https://oauth.yandex.ru/verification_code #временный uri для отладки



        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

---
spring:
  mail:
    host: smtp.mail.ru
    port: 587
    username: TabletopTalks
    password: 12345

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:dev_db
    username: dev
    password: dev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true


---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test_db
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:h2:mem:test_db
    username: prod
    password: prod
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true