server:
  port: 8085

spring:
  profiles:
    active: development

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/db_dev
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/db_test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://production_server:5432/db_prod
    username: prod
    password: prod
    driver-class-name: org.postgresql.Driver