server:
  port: 8085


spring:
  profiles:
    active: development
  security:
    user:
      name: admin
      password: admin

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:h2:mem:dev_db
    username: dev
    password: dev
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test_db
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://localhost:5432/db_prod
    username: prod
    password: prod
    driver-class-name: org.postgresql.Driver